import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function Header() {
  return (
    <header className="bg-blue-500 py-1">
      <div className="mx-auto flex items-center justify-end px-4 py-2">
        <nav className="flex space-x-3">
          <div className="flex items-center">
            <Link href="/" className="hover:text-slate-300">Home</Link>
          </div>
          <div>
            <Link href="/register" className="hover:text-slate-300">Sign Up</Link>
          </div>
          <div>
            <Link href="/login" className="hover:text-slate-300">Login</Link>
          </div>
        </nav>
      </div>
    </header>
  )
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
